### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by Henrietta1989** [kiistala/raspi-mtp-autocopy#1]
Hi!

I tried to install your script but after "sudo adduser $USER fuse" i get:

adduser: The group `fuse` does not exist.

I tried to fix it by using these instructions but it fails too:

http://blog.tordeu.com/?p=50

addgroup: The group `fuse` does not exist.

How i can fix this?

Another things is that is there any way to modify your script so it copies any USB-stick or SD-card not just those which are listed in code?

Thanks

**Comment by kiistala** [comment]
Try sudo addgroup fuse. That creates a group called fuse. However, group membership might not be necessary nowadays. Check that you have fuse installed.

Answer to second question: quite possible, but it complicates the usage of the "shutdown usb stick"
