### ISSUE TITLE
Multiple stick copy

### ISSUE THREAD

**Issue by Henrietta1989** [kiistala/raspi-mtp-autocopy#2]
I don't need unplug2shutdown so i was thinking where i should put "shutdown" so it just shuts down afterwards?

How this script should be modified so it copies any USB-stick or SD-card not just those which are listed in code?

Does it copy or move files? I think most users would prefer moving files.

**Comment by kiistala** [comment]
I guess you could try adding "&& sudo poweroff" after "&& fusermount -u $SOURCEDIR" in copier.sh. I haven't tested this.

If you want the script to always copy files, whatever the inserted device, you need to see the udev documentation. I guess you need a udev rule that applies to all devices. I haven't used one.

It's "raspi-mtp-autocopy", so it copies files. This script was made to fulfill a specific need (backup small CSV files daily to avoid loss of important research data) for a specific project (Tikapuu, University of Jyväskylä) so all users, as far as I know, preferred copying files. In case of needing a more general solution, potential new users are welcome to fork the repo and edit scripts to fulfill their specific needs.
